### ISSUE TITLE
Build automatic sandbox testing on pull request

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#5]
Since Backdrop won't work easily with Simplytest.me, and since we're on a platform that enables this more easily than before, we should look into building an automated sandbox environment for each pull request, similar to Lullabot's setup: http://www.lullabot.com/blog/article/github-pull-request-builder-drupal

However that might be a bit too liberal, we should expect hundreds of pull requests to be open at all times, which could cause some scalability issues. If possible, maybe we could make it optional if a sandbox were needed somehow, like assigning a label on the associated issue. Note that since pull requests aren't in the "issues" repository, we can't assign labels to them.

**Comment by sirkitree** [comment]
Tugboat's goal is to be open source once we get our :hankey: together. There will be a UI component that will be the part we try to monetize.

That being said, there is some interesting work going on using Docker with it, and I've sent the team an email asking if they think this is something Tugboat could even handle, so we'll see what they think.

I personally think it would be nice to have something like this for Backdrop, but also possibly use it as a means of cross promotion for both projects.

**Comment by quicksketch** [comment]
Yeah, I'd love to see tugboat come to fruition. Last I checked with James at Lullabot, it seemed like it wasn't ready to public display (and that was 18 months ago). Since we manage all Backdrop's code repositories publicly, it didn't look like it would be an option in the near future.

**Comment by Gormartsen** [comment]
Sorry I lost track on this issue.
Right now I almost finished git.lc project. 
It is capable to setup new website like pr-NNNN.qa.backdropcms.org based on PR.

Will you be ok to use it to handle this issue?

I will configure it then.

**Comment by Gormartsen** [comment]
@quicksketch @jenlampton 
This task is ready to go production.

Example how it works now.
In my fork: https://github.com/Gormartsen/backdrop

You can see file:
https://github.com/Gormartsen/backdrop/blob/1.x/.gitlc.yml
```yml
deploy:
  branch:
    server: backdrop.vps-private.net
    username: qa
    dir: '{home}/github/branch/{branch}'
    env_vars:
      domain: '{branch}.qa.backdrop.vps-private.net'
      site_name: '{branch} testing site'
      site_mail: 'testing@{branch}.qa.backdrop.vps-private.net'
      account_name: admin
      account_mail: 'testing@{branch}.qa.backdrop.vps-private.net' 
    scripts:
      init: '{deploy_dir}/core/scripts/init_deploy.sh'
    webhooks:
      init: http://github.backdrop.expert/webhook/init
      remove: http://github.backdrop.expert/webhook/remove
  pull_request:
    server: backdrop.vps-private.net
    username: qa
    dir: '{home}/github/pr/{pr_number}'
    env_vars:
      domain: '{pr_number}.qa.backdrop.vps-private.net'
      site_name: '{pr_number} testing site'
      site_mail: 'testing@{pr_number}.qa.backdrop.vps-private.net'
      account_name: admin
      account_mail: 'testing@{pr_number}.qa.backdrop.vps-private.net' 
    scripts:
      init: '{deploy_dir}/core/scripts/init_deploy.sh'
    webhooks:
      init: http://github.backdrop.expert/webhook/init
      remove: http://github.backdrop.expert/webhook/remove
```

It's http://git.lc integration config file.

It deploys a website for each branch and pr.

## branch part
I created branch test. Gitlc created live site http://test.qa.backdrop.vps-private.net
Deploy log is here: 
http://git.lc/Gormartsen/backdrop/deploy/deploy-Gormartsen_backdrop_test-4715
You can find it by clicking 'details' for deploy status. 
<img width="476" alt="screen shot 2016-03-14 at 8 11 35 pm" src="https://cloud.githubusercontent.com/assets/5018896/13764001/27402148-ea21-11e5-9e79-fd5ba8319301.png">

## pull request part
I created PR 10. https://github.com/Gormartsen/backdrop/pull/10

Gitlc created live site http://10.qa.backdrop.vps-private.net/
Deploy log is here: 
http://git.lc/Gormartsen/backdrop/deploy/deploy-Gormartsen_backdrop_10-4717

You can find it by clicking 'details' for deploy status. 
<img width="713" alt="screen shot 2016-03-14 at 8 26 37 pm" src="https://cloud.githubusercontent.com/assets/5018896/13764169/1762a9ba-ea23-11e5-9db9-abf19dba8675.png">

Or see it directly here: http://git.lc/Gormartsen/backdrop

<img width="625" alt="screen shot 2016-03-14 at 8 27 07 pm" src="https://cloud.githubusercontent.com/assets/5018896/13764180/272772b8-ea23-11e5-9085-e5509c4daf9c.png">

## Removing
When branch or PR deleted, website get deleted from server as well.
Example: https://github.com/Gormartsen/backdrop/pull/9
Status provided:
 gitlc/undeploy/pr-9 — I get job satisfaction.
<img width="451" alt="screen shot 2016-03-14 at 8 29 55 pm" src="https://cloud.githubusercontent.com/assets/5018896/13764205/89daab1e-ea23-11e5-8b03-b6470ba32082.png">


## Other details 

You can see webhook pointed to http://github.backdrop.expert 
http://github.backdrop.expert via webhook and qa modules create and destroy domains, database name and user on server backdrop.vps-private.net.
See code here: 
https://github.com/backdrop-ops/github-auto/tree/master/modules/webhook
https://github.com/backdrop-ops/github-auto/tree/master/modules/qa

You can find login and password in deploy log, but we can change so in init_deploy script:
https://github.com/Gormartsen/backdrop/blob/1.x/core/scripts/init_deploy.sh
```sh

#!/bin/sh
# This script create a website based on ENV variables provided by qithab-auto

#set site path
SITEPATH="$HOME/domains/$DOMAIN"

# Go to domain dir
cd $SITEPATH

#link backdrop files
ln -s $GITLC_DEPLOY_DIR/* ./
ln -s $GITLC_DEPLOY_DIR/.htaccess ./

#install backdrop
php $GITLC_DEPLOY_DIR/core/scripts/install.sh --root=$SITEPATH --db-url=mysql://$DATABASE_USER:$DATABASE_PASSWORD@localhost/$DATABASE_NAME --account-mail=$ACCOUNT_MAIL --account-name=$ACCOUNT_NAME --account-pass="$DATABASE_PASSWORD" --site-mail=$SITE_MAIL --site-name="$SITE_NAME"
echo "USER: $ACCOUNT_NAME PASS: $DATABASE_PASSWORD"
```

This script can be a part of repository or can be uploaded on backdrop.vps-private.net server separately.
If it uploaded separately, proper path need to be set into .gitlc.yml  
deploy->branch-> scripts->init 
deploy->pull_request-> scripts->init 

Let me know if it is exactly what you need and I give you instructions how to hook up backdrop/backdrop to http://git.lc and http://github.backdrop.expert


backdrop.vps-private.net - is VPS created to provide websites for this task.
Drop me a public key and I give you SSH access to qa@backdrop.vps-private.net 

Also register on http://dh.it-patrol.com and give me loginname. I will link qa@backdrop.vps-private.net  to this account and you will be able to work with hosting panel.

Example of hosting panel resource usage page:
![screen shot 2016-03-14 at 8 38 10 pm](https://cloud.githubusercontent.com/assets/5018896/13764345/bb6e4cd4-ea24-11e5-865d-a03d8cd0933d.png)
